version: '3.8'

services:
  zephis-core:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINER_TIMEOUT_MS=600000
      - MAX_CONCURRENT_CONTAINERS=10
      - VNC_PORT_RANGE_START=5900
      - VNC_PORT_RANGE_END=5999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - zephis-templates:/app/templates
      - zephis-circuits:/app/circuits
      - zephis-logs:/app/logs
      - ../circuits:/app/src/circuits:ro  # Mount circuits directory as read-only
      - circuit-build-cache:/app/src/circuits/build  # Persistent build cache
    networks:
      - zephis-network
    restart: unless-stopped

  ephemeral-browser:
    build:
      context: ./ephemeral-browser
      dockerfile: Dockerfile
    ports:
      - "5900-5999:5900"
      - "6000-6099:6080"
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    networks:
      - zephis-network
    labels:
      - "zephis=true"
    deploy:
      replicas: 0

networks:
  zephis-network:
    driver: bridge

volumes:
  zephis-templates:
  zephis-circuits:
  zephis-logs:
  circuit-build-cache: